# Recreate original in-memory joins, suppressing their existing file exports.
args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(args[1])
out <- file.path(root, "data", "work", "datasets", "intermediate")
e <- new.env()
e$write_csv <- function(...) invisible(NULL)
e$capture.output <- function(...) invisible(NULL)
source(file.path(root, "code", "original_cleaning_from_cache.R"), local=e)
readr::write_csv(e$final_prev |> dplyr::filter(!is.na(xG_Expected)) |>
  dplyr::mutate(original_clean_row_id=dplyr::row_number()), file.path(out,"original_clean_lineage.csv"))
readr::write_csv(e$transfer_big5_dedup, file.path(out,"original_transfer_dedup_lineage.csv"))
readr::write_csv(e$fbref_dedup, file.path(out,"original_fbref_dedup_lineage.csv"))
readr::write_csv(e$fuzzy_all, file.path(out,"original_fuzzy_replacements.csv"))
original <- readr::read_csv(file.path(root,"data","inputs","reference","clean_data.csv"),show_col_types=FALSE)
stopifnot(isTRUE(all.equal(as.data.frame(original),as.data.frame(e$final_clean),check.attributes=FALSE)))
capture.output(sessionInfo(),file=file.path(out,"phase2_R_sessionInfo.txt"))
